preprocess:
     input: data/raw/realistic_linear_regression_dataset.csv
     output: data/processed/realistic_linear_regression_dataset.csv

train:
 data: data/raw/realistic_linear_regression_dataset.csv
 model: models/model.pkl
 random_state: 42 
 target: SalesRevenue